//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskManagerDBEntities1 : DbContext
    {
        public static TaskManagerDBEntities1 _context;
        public TaskManagerDBEntities1()
            : base("name=TaskManagerDBEntities1")
        {
        }
        public static TaskManagerDBEntities1 GetContext()
        {
            if(_context != null)
            {
                _context = new TaskManagerDBEntities1();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Step> Step { get; set; }
        public virtual DbSet<Task> Task { get; set; }
    }
}
